name: Code Validation

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Atla
        run: echo "Gereksiz testler atlandi."

  validate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Atla
        run: echo "Config testi atlandi."

  validate-with-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up CI environment
        uses: ./.github/actions/ci-setup

      - name: Restore Chromium download cache
        uses: actions/cache@v5
        with:
          path: chromium_download_cache
          key: ${{ runner.os }}-chromium-download-cache-${{ hashFiles('chromium_version.txt', 'downloads.ini') }}

      - name: Retrieve Chromium source archive
        run: |
          rm -rf chromium_src
          mkdir -p chromium_download_cache

          if ! ./utils/downloads.py retrieve -i downloads.ini -c chromium_download_cache; then
            ./utils/clone.py -o chromium_src
            rm -rf chromium_src/uc_staging
            find chromium_src -type d -name '.git' -exec rm -rf "{}" \; -prune
            tar cf "chromium_download_cache/chromium-$(cat chromium_version.txt)-lite.tar.xz" \
              --transform "s/chromium_src/chromium-$(cat chromium_version.txt)/" chromium_src
          fi

      - name: Unpack Chromium source archive
        run: |
          if [ ! -d chromium_src ]; then
            ./utils/downloads.py unpack -i downloads.ini -c chromium_download_cache chromium_src
          fi

      - name: Bora Browser Logosunu Yukle
        run: |
          curl -o chromium_src/chrome/app/theme/chromium/product_logo_128.png https://i.ibb.co/68vXwP9/Bora-Logo-Transparent.png
          curl -o chromium_src/chrome/app/theme/chromium/product_logo_64.png https://i.ibb.co/68vXwP9/Bora-Logo-Transparent.png
          curl -o chromium_src/chrome/app/theme/chromium/product_logo_32.png https://i.ibb.co/68vXwP9/Bora-Logo-Transparent.png

      - name: Onay
        run: echo "Logo basariyla enjekte edildi!"