name: Build DMG

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create DMG
        run: |
          mkdir -p output
          hdiutil create -volname "BoraBrowser" -srcfolder . -ov -format UDZO output/BoraBrowser.dmg

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/BoraBrowser.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
